-- go.nvim format on save
-- https://github.com/ray-x/go.nvim?tab=readme-ov-file#format-on-save
--local format_sync_grp = vim.api.nvim_create_augroup("goimports", {})
--vim.api.nvim_create_autocmd("BufWritePre", {
--  pattern = "*.go",
--  callback = function()
--   require('go.format').goimports()
--  end,
--  group = format_sync_grp,
--})
--
